### ISSUE TITLE
codecov/project fails because threshold is 0%

### ISSUE THREAD

**Issue by thvdveld** [smoltcp-rs/smoltcp#782]
We could fix this by changing the threshold to 1 or 2%, or we could add the following to the `codecov.yml` file:

```yml
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
```

Adding the `informational: true`  will not fail the CI check (I think).

Should we change the config file to one of those?
